/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 363693a92da74628737926c0eff2d856)
interface __BaseEnv_Env {
	ADDRESS_DATA: R2Bucket;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
